version: "3"
services:
    app:
        container_name: docker-node-mongo
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        # environment:
        #     - MONGO_URI=mongodb://mongo:27017/videoLibrary
        # volumes: 
        #     - "./nodeapp:/usr/src/app/nodeapp"
        ports:
            - '9080:3000'
        links: 
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        # restart: always
        ports: 
            - '27017:27017'
