version: "3.2"
services:
    app:
        container_name: docker-node-mongo
        restart: always
        links: 
            - mongo
    angular:
        container_name: angular-client
    mongo:
        container_name: mongo
        image: mongo