version: "3.2"
services:
    app:
        build:
            context: .
        volumes: 
            - "./:/usr/src/app/node-server"
            - "/usr/src/app/node-server/node_modules"
        ports:
            - '3000:3000'
        environment: 
            DEBUG: 'true'
    angular:
        build: 
            context: ./MEANSTACKVIDEOSLIB
            dockerfile: Dockerfile
        volumes: 
            - "./MEANSTACKVIDEOSLIB:/usr/src/app/ng-client"
            - "/usr/src/app/ng-client/node_modules"
        ports: 
            - "7202:4200"
    mongo:
        # env_file: 
        #     - ./node.env
        volumes:
            - type: volume
              source: mongodb_mean
              target: /data/db
        ports: 
            - '27017:27017'
volumes:
    mongodb_mean:
        # external: 
        #     name: mongodb_mean
